title: Comunidade Linux Brasil
email: naotemos@nehumemail.com
description: > # this means to ignore newlines until "baseurl:"
  Se você conhece o Grupo de Telegram sabe que lá é correria!
  Com base nisso decidimos criar um blog com materiais que são comentados e discutidos por lá ;)
baseurl: "/blog"
url: "https://linuxbrasil.github.io"
telegram: "https://telegram.me/LinuxParaTodos"
logo: "/blog/assets/img/logo-linux-brasil.png"
header-img: blog/assets/img/linux-distro-logos.jpg
github_username:  linuxbrasil
highlighter: rouge
permalink: pretty
paginate: 10
comments: true
disqus:
  shortname: https-linuxbrasil-github-io-blog
exclude:
  - Gemfile
  - Gemfile.lock
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate